### ISSUE TITLE
Selection Algorithm [C]

### ISSUE THREAD

**Issue by yashLadha** [iiitv/algos#10]
Suppose you want to find the kth position element in a sorted list without sorting the list, Need to find the median in a Large Data set after Sorting. In these places Selection algorithm can be used.

**Comment by aviaryan** [comment]
@yashLadha Can we have an external link for this algorithm ? like a Wikipedia or some detailed blog post. I think that would help.

**Comment by yashLadha** [comment]
[https://en.wikipedia.org/wiki/Selection_algorithm](https://en.wikipedia.org/wiki/Selection_algorithm) For Selection Algorithm
[https://en.wikipedia.org/wiki/Quickselect](https://en.wikipedia.org/wiki/Quickselect) For Quick Select Algorithm

**Comment by yashLadha** [comment]
I can code this with proper documentation. As it will be for a good practice for algorithms course

**Comment by singhpratyush** [comment]
Removing all other languages than C. Please open issues if you wish to implement in other language.
