### ISSUE TITLE
Breadth First Search [CPP]

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#105]
http://www.geeksforgeeks.org/breadth-first-traversal-for-a-graph/

**Comment by TarunISCO** [comment]
Can I work on this?

**Comment by singhpratyush** [comment]
@TarunISCO: Go ahead.

**Comment by The-Keshav-Agarwal** [comment]
@iiitv/project-maintainers can i work on this issue.

**Comment by yashshah2820** [comment]
@The-Keshav-Agarwal GFI :+1:
