### ISSUE TITLE
One issue per PR and single commit

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#107]
@singhpratyush @aviaryan I think sending one issue per PR and a single commit would be nice rather than adding 2 or more issues in a single PR, what are your views over this?

Edit: @yashLadha @aashutoshrathi What are views about this?

**Comment by singhpratyush** [comment]
It is followed here.

**Comment by Monal5031** [comment]
There was nothing about this in contibuting.md that's why I pointed it out.

**Comment by singhpratyush** [comment]
Please send a PR.

**Comment by Monal5031** [comment]
@singhpratyush  Should I make the changes in the existing PR of Sieve of Eratosthene or make a new PR?

**Comment by singhpratyush** [comment]
This issue would be an irony if you do that.

**Comment by Monal5031** [comment]
@singhpratyush 😆 Ok I'm on it.
