### ISSUE TITLE
Euclidean GCD [C]

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#12]
Finding gcd of two numbers using Eucledian Algorithm. (Recursive and non-recursive both can be implemented).
EDIT:
Link: https://en.wikipedia.org/wiki/Euclidean_algorithm

**Comment by aviaryan** [comment]
@Monal5031 Do you want to implement this in all the languages you have tagged? If not, please specify the languages you want to implement this in, so that others can pick the remaining languages.

**Comment by Monal5031** [comment]
@aviaryan Yes I will implement it in all languages tomorrow afternoon.

**Comment by Monal5031** [comment]
@singhpratyush Should I create two different files : one for recursive and other non-recursive?

**Comment by aviaryan** [comment]
@Monal5031 @singhpratyush Two files sounds good but then we will have to re-consider how we manage the solution links in README.md. 

@singhpratyush One proposal I have got is that let's keep the `[X]` links intact but if an algorithm has 2 or more implementations in a language, we can use `[1]`, `[2]` and so on.

**Comment by Monal5031** [comment]
@aviaryan what if we link `[X]` to the folder of the algorithm and Name the file accordingly.
Like GCD_recursive and GCD_non-recursive

**Comment by aviaryan** [comment]
@Monal5031 Keeping different files for each implementation will make the repo messy. 
If you want to add both implementations, then do it in the same file. 
Eg > `euclidean_gcd.c` has 2 functions, `euclidean_gcd` and `euclidean_gcd_recursive` . 
We are preferring the non-recursive version here because I feel that the non-recursive one would be faster. Is it?

**Comment by Monal5031** [comment]
They are almost the same, but as recursive seems to be easy to remember it is more used than iterative
https://hbfs.wordpress.com/2013/12/10/the-speed-of-gcd/
This link has gcd algo time comparison's.

**Comment by singhpratyush** [comment]
Fixed in f8bf0b0c286f0c14ab3f43c89c7890cecaa94900.
