### ISSUE TITLE
Issue in coin_change_problem

### ISSUE THREAD

**Issue by Prakash2403** [iiitv/algos#121]
Why the base case value is 1? 

Suggestion: Change data type of possibilities to long.

**Comment by singhpratyush** [comment]
There will be one solution: do not include any coins.

**Comment by Prakash2403** [comment]
> There will be one solution: do not include any coins.

But shouldn't the answer be zero then? Formal problem statement says that how many ways can we make the change? Here, number of ways we can give the change is zero. Hence, answer should be zero.

> Would you like to work on it?

I have worked on it. In-fact, I have made a program which calculates the number of possibilities as well as lists all possible possibilities. My code is in Java.

**Comment by yashLadha** [comment]
But is your code prevents the overlapping problem @Prakash2403

**Comment by Prakash2403** [comment]
Yes, I have used DP. No overlapping cases are there.

**Comment by yashLadha** [comment]
for input coins {1,2,3} and to make 4 what is your output?

**Comment by Prakash2403** [comment]
[1,1,1,1] [2,1,1] [2,2] [3,1]

**Comment by yashLadha** [comment]
My code is like : 
`private int dp_sol(int[] ar, int val) {
            int cnt = 0;
            if (val > 0) {
                int length = ar.length;
                for (int i = 0; i < length; i++) {
                    if (ar[i] == val)
                        cnt += 1;
                    else if (ar[i] > val)
                        cnt += 0;
                    else
                        cnt += dp_sol(ar, val - ar[i]);
                }
            }
            return cnt;
        }
`
where `ar : Array of Coins' and 'val : value'

**Comment by yashLadha** [comment]
How u overcomed overlapping @Prakash2403 ?

**Comment by Monal5031** [comment]
@yashLadha You can use the grave accent key three times to show a piece of code as it is. (Just a suggestion).

**Comment by yashLadha** [comment]
@Monal5031 i think i had used it.

**Comment by Monal5031** [comment]
@yashLadha Oh sorry, my browser updated it after my comment.

**Comment by Prakash2403** [comment]
For counting possibilities, I had atored the result in an array. Basically
used the algorithm which Pratyush Sir has used.

For listing paths, I have used an array of arraylist of arraylist of
integers. Array is used for indexing each number from 1 to val. Arraylist
of integers is used for storing a single possibility. Arraylist of
arraylist of integer is used today store all possible paths. If you create
a recursive tree of finding path, you can imagine about dp solution. It is
little bit hard, but it is implementable.

On 01-Apr-2017 10:00 PM, "Yash Ladha" <notifications@github.com> wrote:

How u overcomed overlapping @Prakash2403 <https://github.com/Prakash2403> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iiitv/algos/issues/121#issuecomment-290930864>, or mute
the thread

**Comment by yashLadha** [comment]
In the recursive iteration now u keeped track of duplicates.

**Comment by Prakash2403** [comment]
Actually, in recursive solution, it is not easy to keep track of
duplication. Still if you want, you can maintain a hashmap of key type
set<Integer>and value type integer. Key will be your path and value will be
the corresponding value(given in question).

However, it is easy in DP. Whenever possibility exists, create a new
arraylist and add current coin value in the list. Now, reduce the current
value by current coin value, and using the array, extract all possible
paths for new value and append it to arraylist you just created. Add the
arraylist to arraylist of arraylist of integers as a new possible solution.
Do the same for all possible path you extracted.

**Comment by yashLadha** [comment]
Yaa it can be suppose you had generated 1,1,2 solution now there is a need to increase the second the value to check for possibility and it will become 2. Now 1,2,1 is also a an answer and also get appended   to the list . But they are duplicate solution

**Comment by Prakash2403** [comment]
I am sending code on your clg id

On 01-Apr-2017 10:25 PM, "Yash Ladha" <notifications@github.com> wrote:

Yaa it can be suppose you had generated 1,1,2 solution now there is a need
to increase the second the value to check for possibility and it will
become 2. Now 1,2,1 is also a an answer and also get appended to the list .
But they are duplicate solution

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iiitv/algos/issues/121#issuecomment-290932458>, or mute
the thread

**Comment by yashLadha** [comment]
Ok, you are just storing each instance and appending the previous instances to the new instance including the value of that instance. Nice way @Prakash2403 .

**Comment by Prakash2403** [comment]
Thanks. If you find any better way, please share it with me.

**Comment by singhpratyush** [comment]
@Prakash2403: The answer will be zero only when you have no coins and yet you wish to achieve some final sum that's greater than 0.

Consider this as you are giving a bag which contains coins filled in it, equal to the sum he wishes. How many ways can you return if he wishes no money at all? 1 - give him an empty bag. And what if you have no type of coins and still he wishes some money? 0.

Hope I'm making sense.

**Comment by Prakash2403** [comment]
So you are saying that "no way" is one way possible. I does make sense, but
I have a different solution where we can assign 0 and algorithm still
works.

Interpretation given by you seems correct, but anyways I will post my
solution here once my laptop is repaired. Please review it.

**Comment by singhpratyush** [comment]
Sure!

**Comment by Prakash2403** [comment]
```for(int i=0; i<coins.length;i++)
            for(int j=coins[i];j<=value;j++)
                if(j-coins[i]>0) {
                    possibilities[j]+= possibilities[j-coins[i]];
               else if(j-coins[i] == 0)
                    possibilities[j]+ = 1

This works even if we assign possibilities[0] = 0

**Comment by yashLadha** [comment]
the second case can be removed if we have possibilities[0] = 1;
