### ISSUE TITLE
Issue in stack

### ISSUE THREAD

**Issue by Prakash2403** [iiitv/algos#125]
Standard implementation of stack involves only one pointer, which points at top of stack, It means that if you want to view all items of stack, you must remove all elements and then print them, displayStack() function violates the definition of standard stack.

In java also, there is no implementation of such function. However, if you print the stack, then it will print all the elements. But, as far as I know, it is a property of AbstractList class which is super super super class of Stack. I am aware that when we use inheritance, it inherits all the public properties. But, I guess this is unwanted inherited property. Also, If you visit wikipedia link there is no mention of such property of stack.

[https://en.wikipedia.org/wiki/Stack_(abstract_data_type)](url)

**Comment by Monal5031** [comment]
@Prakash2403 In Java implementation I have used only one pointer I just didn't show it as it was assumed that using LinkedList implementation the top of stack will be considered as the last element of the LinkedList. Further, while displaying the stack I have displayed it in Top-first manner (LIFO). Any mistakes you want to point out over the implementation please share with me. 😃 One thing I could point out is I've used `get()` which doesn't delete the element but only retrieves it (could've used `removeLast()` as per what you are suggesting)

**Comment by Prakash2403** [comment]
I am not raising issues on pointer. I am saying that at any point of time you can only view topmost element. If you see stack implementation on a reputed website/language, you will find that they haven't implemented displayStack() method. 

Only difference between LIFO linked list and stack is you can traverse the LIFO list by making pointer point to next address, but you can't traverse the stack. This limitation is imposed by definition of Stack. 

So, if you are implementing a stack where you allow your program to traverse it, then it is not actually a stack. It is a LIFO linked list.

Please review @singhpratyush @yashLadha

**Comment by yashLadha** [comment]
In the Java documentation of java there is a function search() which returns the 1-based position where an object is on this stack. So basically it is a form of traversal. [link](https://docs.oracle.com/javase/7/docs/api/java/util/Stack.html) @Prakash2403

**Comment by Prakash2403** [comment]
If you see the Java implementation, search method is uses `lastIndexOf(Object o)` property of Vector class which is super class of Stack. I don't know why Java allows such operations. Even in C++, there is no predefined method for stack traversal. In C++, you have to pop out every element in order to view the elements beneath them. If you see Stack definition anywhere, you will find that it is mentioned that only two operations `push(Object o)` and `pop()` method are supported. Even, `peek()` is considered as an **non essential operation**, since it can be implemented by `pop()` followed by `push(Object o)`

I am not sure why Java does so. It's my personal opinion that they should not use such method as it is against the standard definition of Stack.

**Comment by singhpratyush** [comment]
There has been a mistake indeed. Thanks for pointing out @Prakash2403. But I guess that peek should be there, as you can always see the topmost element of a stack (name of top book in the stack) without removing it. What do you think?

Please create a PR resolving this issue.

**Comment by Prakash2403** [comment]
`peek()` should be there. I am just saying that it is a non-essential operation. In Wikipedia article, it is mentioned that stack interface must consist of two methods `push()` and `pop()`. `peek()` method can be implemented using `push()` and `pop()`, hence it is a non-essential operation.

[https://en.wikipedia.org/wiki/Stack_(abstract_data_type)#Non-essential_operations](url)

**Comment by singhpratyush** [comment]
Go ahead with removing peek too.

**Comment by singhpratyush** [comment]
Python Implementation needs to be modified as well.

**Comment by Monal5031** [comment]
@singhpratyush That should go in another issue?

**Comment by singhpratyush** [comment]
@Monal5031: Let's tackle it here.
