### ISSUE TITLE
Binary search on sorted array

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#13]
http://quiz.geeksforgeeks.org/binary-search/

**Comment by Monal5031** [comment]
How about adding a Binary Search on an Almost Sorted array like : [4,5,6,7,8,1,2,3] ?

**Comment by singhpratyush** [comment]
That may go in a new issue.

**Comment by Monal5031** [comment]
#4  is also for Binary Search @singhpratyush

**Comment by singhpratyush** [comment]
Oh!! Didn't saw that. Closing this as duplicate.
