### ISSUE TITLE
Closing PR policy

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#130]
Just a suggestion.
@aviaryan @singhpratyush Shouldn't there be something like if some user is inactive or isn't working on the algorithm then in such case to close the PR and maybe someone else could do it?
Your views over this?

**Comment by aviaryan** [comment]
Yes, we should have something like it. A user blocking an issue for infinite time is surely undesirable. Maybe we can have a rule which says that if a PR has received no commits or activity from the author in 7 days, it will be closed. 
We can add this declaration in the PULL_REQUEST_TEMPLATE file itself.

**Comment by Monal5031** [comment]
Should there be something extra condition like if the person gives any reason then the time maybe exceeded?

**Comment by aviaryan** [comment]
@Monal5031 7 days is pretty sufficient time to implement any algorithm. So if a person is having reasons due to which they can't attend to their issue in 7 days or more, they shouldn't have picked the issue in the first place and they should let the other person do it.

**Comment by Monal5031** [comment]
@singhpratyush Sir your views over this?

**Comment by singhpratyush** [comment]
7 days without extension sounds good.
