### ISSUE TITLE
AVL Trees [Java]

### ISSUE THREAD

**Issue by amany9000** [iiitv/algos#131]
Algorithm to create a balanced binary tree.

http://www.geeksforgeeks.org/avl-tree-set-1-insertion/

**Comment by Monal5031** [comment]
It should come under Data Structure only, also mention the methods above which you intend to implement.

**Comment by Hsankesara** [comment]
I believe nobody is currently working on this issue. @singhpratyush Can you please assign it to me ?

**Comment by singhpratyush** [comment]
Fixed in 7c61a361e55325d135057bb23b313c515ca7b466.
