### ISSUE TITLE
Issue in quick-sort python

### ISSUE THREAD

**Issue by Prakash2403** [iiitv/algos#144]
@aashutoshrathi You have chosen first element as pivot element. This may lead to worst case scenario where time complexity is O(n<sup>2</sup>).  For average case complexity, it is advised to use **median of 3 partitioning technique** . For more information, read [https://www.khanacademy.org/computing/computer-science/algorithms/quick-sort/a/analysis-of-quicksort](https://www.khanacademy.org/computing/computer-science/algorithms/quick-sort/a/analysis-of-quicksort)

Another issue is auxiliary space required by quicksort. You have mentioned that it is O(n), but it can be reduced to O(log N), if algorithm is optimized carefully. For more information, read [https://en.wikipedia.org/wiki/Quicksort#Space_complexity](https://en.wikipedia.org/wiki/Quicksort#Space_complexity).  

What are your views @aviaryan @singhpratyush @yashLadha @saurabhjn76

**Comment by aashutoshrathi** [comment]
@Prakash2403 Should I randomize pivot ?

**Comment by Prakash2403** [comment]
Take three different random temporary pivots, take there median as pivot.
That's median of 3 pivot technique. That will guarantee you that time
complexity will be O(nlogn) with a probability over 65%. This method is
used to avoid worst case.

**Comment by aashutoshrathi** [comment]
@Prakash2403 I tried to randomize pivot, but it went wrong 😕.
Please tell where I went wrong.
[http://ideone.com/aYkFHB](http://ideone.com/aYkFHB)

**Comment by Monal5031** [comment]
@aashutoshrathi There seems to be a very small mistake there, when you take median you will have to iterate through all the elements of array but you have missed the last element in each recursion i.e.
change `for j in range(p, r):` to `for j in range(p, r+1):` on line number 28.

**Comment by aashutoshrathi** [comment]
@Monal5031 I changed `r` to `r+1` still, result isn't sorted.

**Comment by Monal5031** [comment]
@aashutoshrathi Oh sorry, I forgot to mention this one too. `array[p], array[pivot_index] = array[pivot_index], array[p]` is also the cause the trouble.
