### ISSUE TITLE
Dead Link of Counting Sort in README.md

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/algos#173]
Link of Counting Sort in README is redirecting to [https://github.com/iiitv/algos/blob/master/www.geeksforgeeks.org/counting-sort](https://github.com/iiitv/algos/blob/master/www.geeksforgeeks.org/counting-sort) , which is an unavailable page, while it should redirect to [https://www.geeksforgeeks.org/counting-sort](https://www.geeksforgeeks.org/counting-sort)

**Comment by singhpratyush** [comment]
Please send a PR.
