### ISSUE TITLE
Linked List [C]

### ISSUE THREAD

**Issue by sakshee-19** [iiitv/algos#179]
I want to implement this.

**Comment by singhpratyush** [comment]
@sakshee-19: Please add a link to some resource explaining this data structure in the description. Thanks.

**Comment by sakshee-19** [comment]
https://en.wikipedia.org/wiki/Linked_list

**Comment by Prakash2403** [comment]
Why closed it @sakshee-19 ?

**Comment by Prakash2403** [comment]
@sakshee-19 Create a Pull Request from your fork to this repository. Before that, put LinkedList.c file in  linked_list folder.

**Comment by sakshee-19** [comment]
okay
