### ISSUE TITLE
AVL Tree [Java]

### ISSUE THREAD

**Issue by Hsankesara** [iiitv/algos#189]
AVL tree is a self-balancing binary search tree.
To know more : [AVL Tree](https://en.wikipedia.org/wiki/AVL_tree)

**Comment by Hsankesara** [comment]
Can anyone tell me please, Why I cannot add lables and assign myself?

**Comment by Monal5031** [comment]
@Hsankesara The rights of iiitv/algos have modified to read-only, so only admins can do that now.

**Comment by Monal5031** [comment]
@Hsankesara Please read the CONTRIBUTING.md carefully, I will point it out `First make sure you are not suggesting a duplicate.`
Always check if the algorithm you are trying to implement is already implemented or is an open issue.
This algo has an open issue created by @amany9000 in #131 .
