### ISSUE TITLE
Add Counting Sort [Python]

### ISSUE THREAD

**Issue by khilanravani** [iiitv/algos#195]
http://www.geeksforgeeks.org/counting-sort/
Please assign me this and add suitable labels.

**Comment by aviaryan** [comment]
@khilanravani Done.

**Comment by Monal5031** [comment]
@khilanravani Please unassign if you are not working on this.

**Comment by khilanravani** [comment]
Very sorry! Missed the update that I was already assigned

**Comment by khilanravani** [comment]
Will work on it right away..

**Comment by khilanravani** [comment]
Please reassign me... this won't happen again..
