### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#199]
The `.editorconfig` file would help maintain consistency of code for the project.

**Comment by aashutoshrathi** [comment]
I would like to do this, but will need some help regarding GOLang's indentation.

**Comment by aviaryan** [comment]
@aashutoshrathi Golang's indentation is tabs, tab_size = 4, trim_spaces = True, last linefeed = True .. etc

**Comment by aashutoshrathi** [comment]
Should I place file in root of this repo ?
