### ISSUE TITLE
Merge Sort [CPP]

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#20]

**Comment by aviaryan** [comment]
Hey, C and CPP wil have the same code. So I think we should reconsider this. See https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#standalone-points

**Comment by singhpratyush** [comment]
What shall we do in case of vectors and stuff?

**Comment by singhpratyush** [comment]
But that would not be applicable in this case. Closing as duplicate.

**Comment by aviaryan** [comment]
> What shall we do in case of vectors and stuff?

Makes sense. I agree that people can use vectors in place of arrays. But when doing quicksort or mergesort, any programmer would prefer arrays over vectors as `vec[n]` is O(n). 
But suppose you are creating a Binary Indexed Tree, then implementations in C++ and C should differ. C programmer will have to do with functions and pointers whereas C++ one would use a class. 
So I guess this really depends on the algorithm.

**Comment by singhpratyush** [comment]
Correct. We will know when we are going to need CPP implementation too.
