### ISSUE TITLE
Rod Cutting Problem [Python]

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#210]
http://www.geeksforgeeks.org/dynamic-programming-set-13-cutting-a-rod/

**Comment by aashutoshrathi** [comment]
@singhpratyush Sir, `lang-python` instead of `lang-c`

**Comment by singhpratyush** [comment]
Thanks for correcting @aashutoshrathi.

**Comment by aashutoshrathi** [comment]
I'll like to work on this one while @Monal5031 is doing same in C

**Comment by Monal5031** [comment]
@aashutoshrathi Okay you can work on this, I'll edit my comment.

**Comment by aashutoshrathi** [comment]
Assign this to me
