### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#216]
CONTRIBUTING.md needs some updates:
1. Mention of currently accepted languages.
2. Mention use of meaningful function/method names.

**Comment by aviaryan** [comment]
@Monal5031 Please send a PR for the same. Btw, Issue names should point out the issue. Update CONTRIBUTING.md is not a good name for an issue, it should be more like "Contributing.md missing list of currently accepted languages".

**Comment by Monal5031** [comment]
@aviaryan There were things to be updated so I ended up making it only `Update CONTRIBUTING.md`

**Comment by aviaryan** [comment]
@Monal5031 Still it should be like "CONTRIBUTING.md needs update" or "CONTRIBUTING.md missing some points".  Issue title should tell what the problem is.

**Comment by Monal5031** [comment]
Will keep it more descriptive from next time 😄
