### ISSUE TITLE
Euclidean GCD [Java]

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#22]

**Comment by Monal5031** [comment]
I guess I will complete this one too so we can have an example of Java code too.

**Comment by singhpratyush** [comment]
Go ahead.

**Comment by Monal5031** [comment]
What do I name the class for it? As in java, if the name of class and method becomes same it becomes a constructor.

**Comment by singhpratyush** [comment]
Class names are `CamelCase` and method names are `camelCase`. There won't be conflicts,

**Comment by Monal5031** [comment]
EucledianGcd as class name then? I think we cann't add underscores in class names? (Correct me if I am wrong)

**Comment by singhpratyush** [comment]
```java
class EuclideanGCD {
    static void euclideanGCD(int a, int b) {
        ...
    }

    public static void main(String args[]) {
        ...
    }
}
```
