### ISSUE TITLE
Recursive binary search [ C ]

### ISSUE THREAD

**Issue by HarshKhatore** [iiitv/algos#247]
There is no implementation of recursive binary search in c/c++.
Description - [https://en.wikipedia.org/wiki/Binary_search_algorithm](url)

**Comment by singhpratyush** [comment]
Hello @HarshKhatore, thanks for opening the issue.

Please make sure that you are assigned to the issue before working on it. And even if it redundant, please add a link explaining the algorithm in the issue description.

**Comment by HarshKhatore** [comment]
Hello @**singhpratyush**,  thanks for suggesting and assigning my this issue. I have created a pull request regarding this, kindly review it. Ok, I will add the description of the algorithm.
