### ISSUE TITLE
Insertion Sort [Python]

### ISSUE THREAD

**Issue by sirfoga** [iiitv/algos#259]
Bad implementation (i.e not working). The `while` loop [here](https://github.com/iiitv/algos/blob/master/insertion_sort/insertion_sort.py#L9) should be indented one tab right (should be inside the `for` loop).

Description Insertion Sort: https://en.wikipedia.org/wiki/Insertion_sort

**Comment by TarunISCO** [comment]
@aviaryan please assign me

**Comment by sirfoga** [comment]
this is tested (and working correctly)

```python
def insertion_sort(a):
    """
    :param a: list
        List of objects with an order
    :return: list
        Sorted list with insertion sort algorithm
    """

    for i in range(1, len(a)):
        current_value = a[i]
        position = i

        while position > 0 and a[position - 1] > current_value:
            a[position] = a[position - 1]
            position -= 1
            a[position] = current_value

    return a
```
