### ISSUE TITLE
Exponentation by squaring [Python]

### ISSUE THREAD

**Issue by sirfoga** [iiitv/algos#264]
#### This issue is about [Exponentation by squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring).

- [X] Issue Title is in form `Algo/DS Name [Language]`.
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This Algo/DS is worth adding to this repository.
- [X] Assign this issue to me (I want to work on this).
- [X] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by Monal5031** [comment]
@sirfoga Are you implementing this otherwise I'd like to do it?

**Comment by sirfoga** [comment]
Please go on, the implementation is like the [C](https://github.com/iiitv/algos/blob/master/exponentation_by_squaring/exponentation_by_squaring.c) one :+1:
