### ISSUE TITLE
Backtracking algorithm (N-Queen Problem) [Python]

### ISSUE THREAD

**Issue by sirfoga** [iiitv/algos#265]
#### This issue is about [Backtracking algorithm (N-Queen Problem)](https://en.wikipedia.org/wiki/Eight_queens_puzzle).

- [X] Issue Title is in form `Algo/DS Name [Language]`.
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This Algo/DS is worth adding to this repository.
- [X] Assign this issue to me (I want to work on this).
- [X] I will send my PR only after I'm assigned to this issue by any maintainer.

A general solution of the N-Queen problem (any board of n X n) in python with backtracking.

**Comment by sirfoga** [comment]
I intend to pull the algorithm that computes all solutions, is it ok? the [java version](https://github.com/iiitv/algos/blob/master/n_queen_problem/NQueenProblem.java) prints only one solution ..

**Comment by singhpratyush** [comment]
Please use the issue template properly. The heading is supposed to carry the name and link of the algorithm.
