### ISSUE TITLE
Breadth First Search in a Graph [Python]

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#27]
https://en.wikipedia.org/wiki/Breadth-first_search

**Comment by Monal5031** [comment]
Please assign me this one.

**Comment by Monal5031** [comment]
Please unassign me @singhpratyush sir 😄

**Comment by Mangu93** [comment]
Can I be assigned this one and Depth First Traversal?

**Comment by singhpratyush** [comment]
@Mangu93: Please proceed. Thanks :)

**Comment by Mangu93** [comment]
I'll send the PR tomorrow, if you don't mind :)

**Comment by amineHorseman** [comment]
If nobody's working on this issue, please assign me this one.

**Comment by singhpratyush** [comment]
@amineHorseman: Please proceed. Thanks :)
