### ISSUE TITLE
Changing CheckMark in README.md 

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/algos#272]
### [X] in [README.md](https://github.com/iiitv/algos/blob/master/README.md) looks ugly we can replace it 
with  :white_check_mark: or ✔️ or :ballot_box_with_check: or :negative_squared_cross_mark: or :o: .
We can decide which one is good by polls and update it in README.md. 😄 

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by singhpratyush** [comment]
We an use :white_check_mark: (`:white_check_mark:`).

**Comment by aashutoshrathi** [comment]
`(:white_check_mark:)` is giving output as : 
![screenshot 35](https://user-images.githubusercontent.com/21199234/27076566-39cc3db0-504b-11e7-8118-0437151dfba3.png)
Instead of this
![screenshot 36](https://user-images.githubusercontent.com/21199234/27076572-3f7f09ea-504b-11e7-9e8f-3132ee492f0a.png)

**Comment by singhpratyush** [comment]
@aviaryan: What do you think of this?

**Comment by Monal5031** [comment]
We can use circle for showing that the issue/PR of that algo/DS is open, so people don't have to search out the whole list of issues one by one.

**Comment by aviaryan** [comment]
@singhpratyush ✅  is cool 

@Monal5031 That would require regular updates of README.md which is not feasible.

**Comment by singhpratyush** [comment]
Ok then. We'll replace [X] with `:white_check_mark:`.
