### ISSUE TITLE
Improve editorconfig-tools log while testing

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#278]
[`.travis.yml#21`](https://github.com/iiitv/algos/blob/master/.travis.yml#L21) says - 
```sh
editorconfig-tools check **/*
```

It can be modified so that it shows only errors that are encountered - 
```sh
editorconfig-tools check **/* | grep " failed "
```

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by aashutoshrathi** [comment]
- [x] Assign this issue to me (I want to work on this).
