### ISSUE TITLE
JavaScript sample missing in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Anshuman-Verma** [iiitv/algos#288]
- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by singhpratyush** [comment]
Thanks @Anshuman-Verma for reporting. Please proceed with this.

**Comment by Anshuman-Verma** [comment]
Thanks for assigning @singhpratyush, on it.
