### ISSUE TITLE
Trie [Java]

### ISSUE THREAD

**Issue by Prakash2403** [iiitv/algos#29]
https://en.wikipedia.org/wiki/Trie

**Comment by yashLadha** [comment]
I can work upon this.

**Comment by singhpratyush** [comment]
Take up one at a time.

**Comment by yashLadha** [comment]
Now is it fine to work on this?

**Comment by harishkrupo** [comment]
Hold on I already have this ready. 
@yashLadha @aviaryan 
I will share mine. If you want you can hack on it!

**Comment by yashLadha** [comment]
Sure Sir!

**Comment by harishkrupo** [comment]
Need some time though :P

**Comment by yashLadha** [comment]
@harishkrupo if u want i can work upon this. if u don't have time sir.

**Comment by harishkrupo** [comment]
@yashLadha Hey, I actually have it ready. Just not getting the time to make a little changes and upload it. Will do it.

**Comment by jsroyal** [comment]
Should I send PR?
