### ISSUE TITLE
Shell Sort [JavaScript]

### ISSUE THREAD

**Issue by mohitkyadav** [iiitv/algos#290]
#### This issue is about [Shell Sort](https://en.wikipedia.org/wiki/Shellsort).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by singhpratyush** [comment]
@mohitkyadav: Please correct the issue description.
