### ISSUE TITLE
Quick Select  [Python]

### ISSUE THREAD

**Issue by Hsankesara** [iiitv/algos#292]
#### This issue is about [Quick Select](https://en.wikipedia.org/wiki/Quickselect).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
Please assign these issue to me.

**Comment by singhpratyush** [comment]
@Hsankesara: Please correct issue description.

**Comment by Monal5031** [comment]
Why isn't the first point ticked? Issue title is as it should be.

**Comment by Hsankesara** [comment]
What are you talking about. First point is ticked

**Comment by Anshuman-Verma** [comment]
He means kindly correct the first point in **Issue Description.**

**Comment by Hsankesara** [comment]
I think I'll correct it.
