### ISSUE TITLE
Linear Search [JavaScript]

### ISSUE THREAD

**Issue by Anshuman-Verma** [iiitv/algos#294]
#### This issue is about [Linear Search](https://en.wikipedia.org/wiki/Linear_search).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by Monal5031** [comment]
@Anshuman-Verma if you are working on #293 currently, can I work on this if its okay with you?

**Comment by Anshuman-Verma** [comment]
#293 is done.
