### ISSUE TITLE
Binary Search [JavaScript]

### ISSUE THREAD

**Issue by Anshuman-Verma** [iiitv/algos#295]
#### This issue is about [Binary Search](https://en.wikipedia.org/wiki/Binary_search_algorith).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by singhpratyush** [comment]
@Anshuman-Verma: Please complete previously assigned issues first.

**Comment by Monal5031** [comment]
@singhpratyush Please assign me this one.
