### ISSUE TITLE
Issue template needs update

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#298]
@singhpratyush @aviaryan sir should there be another point that in issue template that if the assignee fails to send a PR within 7 days after assignment, they will be unassigned from the issue, so that we don't have issues blocked. Also the number of issues at a time we can work on should also be mentioned.

**Comment by mohitkyadav** [comment]
@Monal5031  That'll be reasonable.

**Comment by Anshuman-Verma** [comment]
Fair Enough

**Comment by aashutoshrathi** [comment]
Seems Legit

**Comment by aashutoshrathi** [comment]
Is anyone doing work on this one ?
Can I work on this ?

**Comment by Monal5031** [comment]
@aviaryan sir please assign this to @aashutoshrathi

**Comment by aashutoshrathi** [comment]
- [x] Assign me
