### ISSUE TITLE
Modular Exponential [JavaScript]

### ISSUE THREAD

**Issue by Anshuman-Verma** [iiitv/algos#299]
#### This issue is about [Modular Exponential](https://en.wikipedia.org/wiki/Euclidean_algorithm).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.

**Comment by singhpratyush** [comment]
@Anshuman-Verma: Please complete previously assigned issues first.

**Comment by aashutoshrathi** [comment]
@Anshuman-Verma Can I work on this one ?

**Comment by Anshuman-Verma** [comment]
All yours @aashutoshrathi :smile:

**Comment by aashutoshrathi** [comment]
- [x] Assign me this issue.
