### ISSUE TITLE
Possible Algo. List and Difficulty level

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#3]
We can compile a possible list of Algorithms to be implemented so that a person attempting as a beginner will not have much problem.
Further, I guess it would be nice to assign the work to implement the algorithms according to the difficulty level. Like a person who is familiar with coding will not attempt beginner level programs and maybe leave them for the new one's. Also, a time constraint would also be a good thing to add so that someone else who is ready to do it will get that chance.

**Comment by yashLadha** [comment]
See what we can do is that we can assign tags to every issue and can create a tag based assignment to every year students.

**Comment by aviaryan** [comment]
@Monal5031 @yashLadha Sounds good.. We can create tags like `easy`, `medium`, `hard` and `expert`.

**Comment by aviaryan** [comment]
This has been implemented, hence closing..
