### ISSUE TITLE
Separate section for Standard Problems

### ISSUE THREAD

**Issue by Anshuman-Verma** [iiitv/algos#300]
We have a couple of standard standard problems like *coin change problem, rod cutting problem etc.*.

Should we have a separate section for their implementations ?

**Comment by Monal5031** [comment]
@Anshuman-Verma something similar was discussed before, but nothing came out of it.
still its worth a discussuon.
Views? @singhpratyush @aviaryan @Prakash2403 @yashLadha @aashutoshrathi @mohitkyadav

**Comment by singhpratyush** [comment]
@Anshuman-Verma: See #148.

**Comment by singhpratyush** [comment]
I have reopened #148. We can continue the discussion there.

**Comment by Anshuman-Verma** [comment]
Alright.
