### ISSUE TITLE
CONTRIBUTING.md missing to state JS contributions

### ISSUE THREAD

**Issue by Anshuman-Verma** [iiitv/algos#315]
> Currently we are accepting contributions in C, C++, Java, Python and Go but other languages may be considered after a discussion.

Since we have started JavaScript submissions too, so we need to add JS there as well.

**Comment by aashutoshrathi** [comment]
Can I work on this ? 😆

**Comment by Anshuman-Verma** [comment]
Hard luck, my other issue just got merged :laughing:

**Comment by Anshuman-Verma** [comment]
Do we really need a PR for this @aviaryan ?

**Comment by aviaryan** [comment]
Yes please send a PR. Will you like to work on this?

**Comment by Anshuman-Verma** [comment]
Yes, assign me please :+1:
