### ISSUE TITLE
Prime Factor [Python]

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/algos#323]
#### This issue is about [Prime Factor](https://en.wikipedia.org/wiki/Prime_factor).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by Lucifer24** [comment]
-[x] Assign this issue to me.
