### ISSUE TITLE
Add a PULL REQUEST TEMPLATE

### ISSUE THREAD

**Issue by aviaryan** [iiitv/algos#34]
It should specifically remind people to have a look at the CONTRIBUTING guidelines before submitting their patch. Also some keys points from the guidelines should be listed out. 

Example: https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by yashLadha** [comment]
Also mention that there should one commit per PR and not more than that.
