### ISSUE TITLE
Fixing Travis for C++ [Threading]

### ISSUE THREAD

**Issue by yashLadha** [iiitv/algos#366]
This Issue targets the PR #349 and also the upcoming PR's in C++, which uses threads. This compilation flag will resolve the errors in the tests in travis-ci currently. :smile:

**Comment by aviaryan** [comment]
Please explain what the issue is and how it can be fixed.

**Comment by yashLadha** [comment]
This issue is about the PR #349  , travis is flagging that thread flag hasn't passed during compilation, so i add it correcting the travis-ci issue of PR #349 . Hope it helps.
