### ISSUE TITLE
Changing Folder name of Quick Sort

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/algos#402]
#### Folder name of Quick Sort should be `quick_sort` instead of `quicksort`, as we followed that style in naming other folders. Also Entry in README.md has name as `Quicksort` instead of `Quick Sort`

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this), if this change should be done.
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by aashutoshrathi** [comment]
Maintainers,
If issue is not necessary please close it.

**Comment by singhpratyush** [comment]
@aashutoshrathi: Please proceed with the corrections.
