### ISSUE TITLE
k-NN Algorithm [Python]

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#41]
https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm

**Comment by singhpratyush** [comment]
Well, I really don't understand the criteria for `difficulty-hard`, `difficulty-medium`, ... Can anyone help.

**Comment by aviaryan** [comment]
@singhpratyush It is inspired from Codechef/Hackerrank standards. A simple binary search based question will go in Easy level on these sites, so "Binary search" is `difficulty-easy` here. 
Trie-based questions and basic DP questions generally go in medium level, hence `difficulty-medium` here. Same goes..

**Comment by singhpratyush** [comment]
But they generally do not ask for k-NN algoithms? What about this?
