### ISSUE TITLE
Fixing Travis Build Fail in linkedList.js

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/algos#416]
#### This issue is about Travis Build.
```
linked_list/linkedList.js
|  34| »   »   return;
|    | [NORMAL] HappinessLintBear:
|    | Unnecessary return statement.
linked_list/linkedList.js
|  77| »   »   return;
|    | [NORMAL] HappinessLintBear:
|    | Unnecessary return statement.
Executing section cli...
```
*Due to this, Travis Build of other PRs are failing. This issue was not raised by Travis in it's own PR.*

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by Anshuman-Verma** [comment]
:angry:
