### ISSUE TITLE
Segment Tree [C]

### ISSUE THREAD

**Issue by HarshKhatore** [iiitv/algos#422]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

Link - [https://en.wikipedia.org/wiki/Segment_tree](url)

**Comment by Monal5031** [comment]
Update the links in issue description @HarshKhatore

**Comment by Monal5031** [comment]
@HarshKhatore Unassigned you due to inactivity, Please get it reassigned if you wish to send a PR.

**Comment by vidit2512** [comment]
@AmanRaj1608 I want to work on this issue.

**Comment by AmanRaj1608** [comment]
@vidit2512 GFI
