### ISSUE TITLE
Change color of badge in README

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#434]
The `Open source` and `License` badge in README needs a color change, as white is not visible.
- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by mohitkyadav** [comment]
on it.
