### ISSUE TITLE
Fibonacci Number [Java]

### ISSUE THREAD

**Issue by jsroyal** [iiitv/algos#444]
#### This issue is about [Fibonacci Number](http://www.geeksforgeeks.org/program-for-nth-fibonacci-number/).

- [X] Issue Title is in form `Algo/DS Name [Language]`.
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This Algo/DS is worth adding to this repository.
- [X] Assign this issue to me (I want to work on this).
	- [X] I ensure that I am not already assigned to 2 or more issues.
- [X] I will send my PR only after I'm assigned to this issue by any maintainer.
- [X] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by aashutoshrathi** [comment]
Change this #### This issue is about [Algo/DS Name](link to resource for the Algo/DS).
 to #### This issue is about [Fibonacci Number](http://www.geeksforgeeks.org/program-for-nth-fibonacci-number/).

**Comment by ribhav-pahuja** [comment]
I want to work on this.

**Comment by singhpratyush** [comment]
@ribhav-pahuja: @jsroyal is already working on it. You can check other issues in this repository.

**Comment by mohitkyadav** [comment]
@shikherjaiswal 👍

**Comment by Monal5031** [comment]
@shikherjaiswal go ahead send a PR, make sure you read the guidelines first.

**Comment by heisenberg-2505** [comment]
Hi, can I add the code for the nth Fibonacci number in other languages?

**Comment by aashutoshrathi** [comment]
@heisenberg-2505 Yes. Make sure it is not already available using README.

**Comment by heisenberg-2505** [comment]
Okay, should I open an issue for this?

**Comment by mohitkyadav** [comment]
Sure @heisenberg-2505 👍
