### ISSUE TITLE
Add a code of conduct for the repository.

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#451]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS).

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by mohitkyadav** [comment]
@Monal5031 You are already assigned to 2 issues, please uncheck relevent points.

**Comment by Monal5031** [comment]
@singhpratyush Sir shall I proceed with this one? I cannot see the `community` button under insights, is it possible that only owner can see it, as I'm able to see it in ChefLib.

**Comment by singhpratyush** [comment]
@Monal5031: Please proceed with the issue. Thanks.

**Comment by Monal5031** [comment]
@singhpratyush sir any particular email address which I should fill in the CODE_OF_CONDUCT.md?

**Comment by singhpratyush** [comment]
Please avoid it if it is optional.
