### ISSUE TITLE
Add How to run them for C#

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/algos#454]
#### This issue is about updating How to run them.

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by Monal5031** [comment]
Also the tests need to be updated to execute c# files.

**Comment by aashutoshrathi** [comment]
Anyone who can work on this?

**Comment by mohitkyadav** [comment]
I would like to work on this. after #433 is merged.
