### ISSUE TITLE
Remove issues pointed by Codacy

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/algos#456]
#### This issue is about [Codacy code check issues](https://www.codacy.com/app/iiitv/algos/dashboard).

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by aashutoshrathi** [comment]
- [x] Assign this issue to me ( I can work on this).

**Comment by devshiva619** [comment]
@singhpratyush Hey I would like to work on this

**Comment by devshiva619** [comment]
@Monal5031 can I go on with this one ?

**Comment by devshiva619** [comment]
@singhpratyush @Monal5031 I am with rectifying the issues showed in Codacy. If you assign it to me then I will send the PR as mentioned above. :smiley:

**Comment by singhpratyush** [comment]
@devshiva619: Please proceed with the issue.

**Comment by devshiva619** [comment]
@singhpratyush Hey should I send the PR. But I have not been assigned yet, will it be fine?

**Comment by singhpratyush** [comment]
@devshiva619: Yes. Please proceed.
