### ISSUE TITLE
Merge Sort [C#]

### ISSUE THREAD

**Issue by DimaMukhin** [iiitv/algos#473]
#### This issue is about [Merge Sort](https://www.khanacademy.org/computing/computer-science/algorithms/merge-sort/a/overview-of-merge-sort).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by AkshGautam** [comment]
Assign this issue to me (I want to work on this).

**Comment by aashutoshrathi** [comment]
@AkshGautam, @DimaMukhin is already assigned to this one, explore other issues on the repository.

**Comment by bunyy** [comment]
Add me for solving this issue

**Comment by Monal5031** [comment]
@bunyy  Sorry but this issue is already assigned to @DimaMukhin  please go through other issues in the repo. You will surely find more.
