### ISSUE TITLE
SleepSort [Java]

### ISSUE THREAD

**Issue by ashutosh-wad** [iiitv/algos#490]
#### This issue is about adding a SleepSort implementation in Java.

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by riktimmondal** [comment]
i would like to work on this

**Comment by singhpratyush** [comment]
@riktimmondal: @ashutosh-wad is already working on it. You can take a look at other issues or create a new one and work on it.

**Comment by singhpratyush** [comment]
@ashutosh-wad: Thanks for contributing.

Can you change other implementations in the similar way where the sleep time is scaled according to numbers?
