### ISSUE TITLE
Add more helpful resources to README

### ISSUE THREAD

**Issue by aviaryan** [iiitv/algos#5]
Please add more algorithm lists / tutorial lists / related materials etc to the **Resources** section of the README.

**Comment by Monal5031** [comment]
Check out this link : https://github.com/Monal5031/awesome-competitive-programming
It has a whole list of reading materials, links and much more.

**Comment by aviaryan** [comment]
@Monal5031 Going through that list can be exhaustive. Do you have any particular favorites that we can add to our **Resources** list? I think we should link to the `awesome-competitive-programming` repo too as it contains lots of related materials.

**Comment by singhpratyush** [comment]
>  I think we should link to the awesome-competitive-programming repo too as it contains lots of related materials.

:+1:

**Comment by Monal5031** [comment]
https://github.com/Monal5031/stanfordacm
This repo contains the codes written by ACM teams and coaches of stanford. It might be somewhat useful I think.

**Comment by yashLadha** [comment]
We should use the link to the original repo, if u don't mind @Monal5031

**Comment by aviaryan** [comment]
@Monal5031 Please send necessary PRs.

**Comment by Monal5031** [comment]
@yashLadha Yeah i'll link it to the original repo

**Comment by singhpratyush** [comment]
Do we need more?
