### ISSUE TITLE
Stack [C#]

### ISSUE THREAD

**Issue by franetheman** [iiitv/algos#501]
#### This issue is about [Stack.](http://www.cdn.geeksforgeeks.org/stack-data-structure-introduction-program/)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@singhpratyush

**Comment by franetheman** [comment]
@singhpratyush Could you assign me to it as well?

**Comment by singhpratyush** [comment]
@franetheman: Done. Please proceed with the issue.
