### ISSUE TITLE
Bug in C# sample code from CONTRIBUTING.md

### ISSUE THREAD

**Issue by DimaMukhin** [iiitv/algos#503]
#### This issue is about a bug in the C# sample code from the [CONTRIBUTING.md](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) file.

The sample code is wrong for C# and will produce the following error:
"'QuickSort': member names cannot be the same as their enclosing type"
This can be easily fixed by changing the method "QuickSort" into "DoQuickSort"

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@aashutoshrathi

**Comment by singhpratyush** [comment]
@mohitkyadav @aashutoshrathi: Please see if we need to make this change.

**Comment by mohitkyadav** [comment]
Yes @singhpratyush this change is needed. @DimaMukhin Please proceed with this issue.

**Comment by aashutoshrathi** [comment]
Yes, @singhpratyush this change is needed.
