### ISSUE TITLE
Queue [Python]

### ISSUE THREAD

**Issue by sebasrp** [iiitv/algos#510]
#### This issue is about [Queue](http://www.cdn.geeksforgeeks.org/stack-data-structure-introduction-program/).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@manish1997

Possible duplicate or related issues are:

- #345: Gradient Descent [Python]
- #478: Algo/largest_sum_contiguous_subarray [C++]
- #391: Shell Sort [Java]
- #428: Add badges to README.md
- #427: Sleep Sort [Golang]

**Comment by amineHorseman** [comment]
Can I be assigned to this issue if no one's working on it?

**Comment by sebasrp** [comment]
go for it - i am not going to be able to meet the required 'submit a PR within a week of issue creation'
