### ISSUE TITLE
Issue in stack(C#) implementation

### ISSUE THREAD

**Issue by Prakash2403** [iiitv/algos#517]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS).

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

`Rotate` and `ToString` method traverses the stack without popping out it's elements. This is not allowed in Stack. A similar discussion is done in issue #125 . Please look into it. @singhpratyush @Monal5031 @aashutoshrathi @yashLadha @aviaryan .

**Comment by Monal5031** [comment]
Yes @Prakash2403 sir, definitely a bug 😄

**Comment by singhpratyush** [comment]
@franetheman: Would you like to fix this?

**Comment by Monal5031** [comment]
@Prakash2403 Sir would you take this otherwise lets label this `up for grabs`

**Comment by Prakash2403** [comment]
@Monal5031 Don't know C#. Labelling it `up for grabs`.

**Comment by PlatanoBailando** [comment]
@Prakash2403 I can try this one

**Comment by singhpratyush** [comment]
@PlatanoBailando: Please proceed with the issue. Thanks :)
