### ISSUE TITLE
Prims [JavaScript]

### ISSUE THREAD

**Issue by Batschkoto** [iiitv/algos#525]
#### This issue is about [Prims](https://en.wikipedia.org/wiki/Prim%27s_algorithm)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@Monal5031

Possible duplicate or related issues are:

- #345: Gradient Descent [Python]
- #478: Algo/largest_sum_contiguous_subarray [C++]
- #428: Add badges to README.md
- #328: Issue template has a unnecessary tabpsace in point 5.
- #391: Shell Sort [Java]

**Comment by Batschkoto** [comment]
@singhpratyush Could you please add the Hacktoberfest label to the issue?

**Comment by singhpratyush** [comment]
@Batschkoto: Done :)
