### ISSUE TITLE
NQueen Problem [Java]

### ISSUE THREAD

**Issue by gaijinco** [iiitv/algos#542]
#### This issue is about NQueenProblem Java (https://github.com/iiitv/algos/blob/master/n_queen_problem/NQueenProblem.java).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [X] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

I think the current implementation can be improved. First, code doesn't use Java strengths at all, the same implementation could be done in non OOP-languages. Second, code is really low level so while it works, is hard to understand at first glance. I think algorithms should be code in a Clean Code manner so that anyone can understand what they do.

I would like to code an OOP solution using better levels of abstractions on methods.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@singhpratyush

**Comment by singhpratyush** [comment]
@gaijinco: Can you please give an outline of how will you be improving it? What structure will you follow?

**Comment by gaijinco** [comment]
@singhpratyush as I mentioned, the solution is not OOP. In the literature there's usually no mention of any solution like this, and that's why I think is cool to do it. An OOP solution will have a class NQueen which I can build with some parameters (at least size, probably queens already placed) and have an iterator method which returns an Iterator to the solution for the given configuration. Also a configuration shouldn't be something low level like an array but a class which at least has a toString method that let's get a nice String representation. That'd be my approach.

**Comment by singhpratyush** [comment]
@gaijinco: Cool! Waiting to see the implementation. :)
