### ISSUE TITLE
BinarySearch [Java]

### ISSUE THREAD

**Issue by gaijinco** [iiitv/algos#543]
#### This issue is about BinarySearch [Java] (https://github.com/iiitv/algos/blob/master/binary_search/BinarySearch.java).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

The operation int mid = (left + right) / 2; can cause overflow issues, should be changed to int mid = left + (right - left) / 2; to avoid that.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@Monal5031

**Comment by callensm** [comment]
I can fix this if no one else is going to be assigned.

**Comment by singhpratyush** [comment]
@callensm: @gaijinco asked for assignation while opening the issue. You can try out other open issues :)
