### ISSUE TITLE
Sieve Of Eratosthenes [Java]

### ISSUE THREAD

**Issue by gaijinco** [iiitv/algos#583]
#### This issue is about Sieve Of Eratosthenes [Java] (https://github.com/iiitv/algos/blob/master/sieve_of_eratosthenes/SieveOfEratosthenes.java).

- [x] Issue Title is in form `Sieve Of Eratosthenes [Java]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

I think the code can be improved in 2 ways:

1. Making it more OOP so that there's a class with a method isPrime(int) and internally uses a sieve.
2. We can use the principle of not mixing levels of abstraction to have code that's really simple to understand, with methods that are mostly written like prose and methods that hide the implementation details behind methods and with good names that explain better the low level details of the algorithm.

**Comment by singhpratyush** [comment]
The contributors most likely able to help are:

@singhpratyush
