### ISSUE TITLE
Binary Search [python]

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#59]

**Comment by aashutoshrathi** [comment]
iterative or recursive, which should I work on?
which one is faster ?

**Comment by Monal5031** [comment]
You can work upon both and test for both as I did for eucidean GCD

**Comment by aashutoshrathi** [comment]
@Monal5031 ok, thanks 👍

**Comment by rajeeviiit** [comment]
@aashutoshrathi 
Are you working on it ?

**Comment by aashutoshrathi** [comment]
Yes @rajeeviiit
