### ISSUE TITLE
Printing  single linked list in reverse order

### ISSUE THREAD

**Issue by kurianbenoy** [iiitv/algos#609]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS).

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by singhpratyush** [comment]
[GitMate.io](https://gitmate.io) thinks possibly duplicate or related issues are #345 (Gradient Descent [Python]), and #328 (Issue template has a unnecessary tabpsace in point 5.).

**Comment by kurianbenoy** [comment]
Cant understand it mate . Should I edit the Issue?

**Comment by kurianbenoy** [comment]
can you assign me this issue?
