### ISSUE TITLE
Fibonacci Number [C]

### ISSUE THREAD

**Issue by heisenberg-2505** [iiitv/algos#628]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by aashutoshrathi** [comment]
@heisenberg-2505 One Issue per algo in one language and one PR for one issue.
Please stick to the rules.

**Comment by heisenberg-2505** [comment]
Is this fine?

**Comment by gateway2rohan** [comment]
Assign this issue to me

**Comment by ican8** [comment]
Can I contribute to this issue?

**Comment by aashutoshrathi** [comment]
Yeah sure. @ican8

**Comment by The-Keshav-Agarwal** [comment]
please assign this task to me. I would like to work on this issue.

**Comment by aashutoshrathi** [comment]
Go ahead! @The-Keshav-Agarwal
