### ISSUE TITLE
Binary Search [C++]

### ISSUE THREAD

**Issue by abhiy13** [iiitv/algos#643]
#### This issue is about [Binary Search](https://en.wikipedia.org/wiki/Binary_search_algorithm).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by shivang-chhabra** [comment]
can i resolve this issue?

**Comment by gateway2rohan** [comment]
Assign this issue to me

**Comment by sam20code** [comment]
@iiitv/project-maintainers    I want to work on this issue

**Comment by yashshah2820** [comment]
@sam20code you already have two issues assigned to you, create PRs for them then you can take this issue if no one asks for it in the mean time

**Comment by jatin0814** [comment]
I want to work on this issue @iiitv/project-maintainers

**Comment by jatin0814** [comment]
@yashshah2820 sir can u please assign it to me

**Comment by yashshah2820** [comment]
tag @iiitv/project-maintainers not any individual.

**Comment by yashshah2820** [comment]
@jatin0814 don't create a PR until the issue is assigned to you.

**Comment by himanshusanecha** [comment]
If possible i want to work on this issue @iiitv/project-maintainers

**Comment by jatin0814** [comment]
I already tagged  @iiitv/project-maintainers

**Comment by yashshah2820** [comment]
since @jatin0814 asked first so it will be fair enough to assign the issue to him  
GFI 👍

**Comment by himanshusanecha** [comment]
no problem sir i will find another one @yashshah2820 😄

**Comment by Ayush-Khandelwal28** [comment]
I want to work on the issue, I will also update README. @iiitv/project-maintainers
