### ISSUE TITLE
Soundex Algorithm [Java]

### ISSUE THREAD

**Issue by meetpaija** [iiitv/algos#663]
#### This issue is about [Soundex Algorithm](https://en.wikipedia.org/wiki/Soundex).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by AkshatDobriyal** [comment]
@iiitv/project-maintainers I want to work on this issue.

**Comment by ishanksoni** [comment]
@AkshatDobriyal  GFI :+1:
