### ISSUE TITLE
Data structures in this list?

### ISSUE THREAD

**Issue by aviaryan** [iiitv/algos#69]
I think we should include DS in this list too. I mean they are very related to the algorithms and are often used in algorithms. Examples - implementation of Stack, Queue, Heap etc.

Please post your views regarding this. @singhpratyush @Monal5031 @yashLadha @aashutoshrathi @jsroyal

**Comment by jsroyal** [comment]
@aviaryan Yeah! Sure! I was also thought about it.It will be good to cover all data structure in various language.

**Comment by yashLadha** [comment]
We can Have data structures like segment trees, persistent data structures, AVL etc. Its a good issue as our first year currently have data structure course ongoing , so it is a good opportunity for them to explore this domain. @Monal5031

**Comment by singhpratyush** [comment]
> I mean they are very related to the algorithms and are often used in algorithms.

Indeed.

Can't we simply open issues for various data structures and (someone would) implement them? Will it conflict the current policies?

**Comment by Monal5031** [comment]
@aviaryan @yashLadha @singhpratyush @jsroyal 
It would be nice to add DS to this as many algorithms will also need them at some point and with our DS subject ongoing now it would be nice practise for us too.
But we need to fix that what work we have to display for any DS (e,g, insert, delete, etc)

**Comment by singhpratyush** [comment]
> But we need to fix that what work we have to display for any DS

That can be discussed while defining the issue for the DS. We can't generalize it as each DS will have different requirements.

**Comment by aviaryan** [comment]
> @singhpratyush: Can't we simply open issues for various data structures and (someone would) implement them? Will it conflict the current policies?

No, it wouldn't. Though DS hasn't been mentioned anywhere in the README so it could be somewhat confusing to see a DS issue. One needs to update the README and include that this is a list of DS too.

**Comment by jsroyal** [comment]
@singhpratyush >We can't generalize it as each DS will have different requirements.

We can generalize basic operation for all most DS.
Like eg. insert , delete, search,display.

**Comment by Monal5031** [comment]
@aviaryan Can we make use of the project section in the repo specially for DS?

**Comment by aviaryan** [comment]
@Monal5031 How do you plan to do so? 
Projects are like trello boards, I don't see how one can use them for this.

**Comment by singhpratyush** [comment]
I agree with the idea of adding data structures in the repo. Further I feel like things would go just the way they are even if we add this. We will just need to add some information with each issue as there will be no fixed problem statement for such issues.

**Comment by aviaryan** [comment]
So it's decided then. @singhpratyush Can you please create a sample issue for adding "stack" implementation ? I am closing this issue now.

**Comment by aviaryan** [comment]
Just remembered we need to update the documentation about this change. 
Please see and review #79 for that.
