### ISSUE TITLE
Sorting/Heapsort[C++]

### ISSUE THREAD

**Issue by nlok5923** [iiitv/algos#690]
#### This issue is about [Sorting/Heap sort](https://www.google.com/amp/s/www.geeksforgeeks.org/heap-sort/amp/)

- [x] Issue Title is in the form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by nlok5923** [comment]
> #### This issue is about [Algo/DS Name](link to resource for the Algo/DS).
> * [x]  Issue Title is in form `Algo/DS Name [Language]`.
> * [x]  I searched or browsed the repo’s other issues to ensure this is not a duplicate.
> * [x]  This Algo/DS is worth adding to this repository.
> * [x]  Assign this issue to me (I want to work on this).
>   
>   * [x]  I ensure that I am not already assigned to 2 or more issues.
> * [x]  I will send my PR only after I'm assigned to this issue by any maintainer.
> * [x]  I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

@iiitv/project-maintainers i would like to work on this issue

**Comment by yashshah2820** [comment]
@nlok5923 fill the `Algo/DS Name [Language]` details :)

**Comment by nlok5923** [comment]
> @nlok5923 fill the `Algo/DS Name [Language]` details :)

Heap sort[C++]

**Comment by nlok5923** [comment]
@yashshah2820 Sir is it fine now do let me know.

**Comment by yashshah2820** [comment]
link to any resources as mentioned in the issue body

**Comment by nlok5923** [comment]
> link to any resources as mentioned in the issue body

@yashshah2820 added the resource link.

**Comment by yashshah2820** [comment]
@nlok5923 go for it 👍
