### ISSUE TITLE
Sorting/Insertion sort[C++]

### ISSUE THREAD

**Issue by nlok5923** [iiitv/algos#691]
#### This issue is about [Sorting/insertion sort](https://www.google.com/amp/s/www.geeksforgeeks.org/insertion-sort/amp/)

- [x] Issue Title is in the form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

@iiitv/project-maintainers I would like to work on this issue

**Comment by yashshah2820** [comment]
fill the [Algo/DS Name] and add the resource link if any.

**Comment by nlok5923** [comment]
@yashshah2820 is it fine now sir

**Comment by yashshah2820** [comment]
any links to the DS if you have then mention it the "link to resource for the Algo/DS"

**Comment by nlok5923** [comment]
> any links to the DS if you have then mention it the "link to resource for the Algo/DS"
@yashshah2820 added the resource link
