### ISSUE TITLE
Breadth First Traversal [C++]

### ISSUE THREAD

**Issue by Monik09** [iiitv/algos#693]
#### This issue is about [Breadth First Traversal](https://www.cs.bu.edu/teaching/c/tree/breadth-first/)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by yashshah2820** [comment]
@Monik09 follow the format add details to [Algo/DS Name](link to resource for the Algo/DS).

**Comment by Monik09** [comment]
> @Monik09 follow the format add details to [Algo/DS Name](link to resource for the Algo/DS).

is this fine now?

**Comment by Monik09** [comment]
Can i now work on it?

**Comment by ishanksoni** [comment]
go for it!

**Comment by Monik09** [comment]
@ishanksoni i saw a duplicate tag but when I search for breadth first traversal in C++ in iiitv/algos repo there is no repo of this name. And even iiitv/algos repo main page has no file for breadth first traversal. So can i know why this tag  has been added.

**Comment by ishanksoni** [comment]
@Monik09 I added duplicate tag as, the similar issue has been created already :)

**Comment by Monik09** [comment]
@ishanksoni I think I should close this issue then and unassign myself?

**Comment by ishanksoni** [comment]
@Monik09 Yeah that's seems right :+1:
