### ISSUE TITLE
Double Ended Queue [C]

### ISSUE THREAD

**Issue by Monik09** [iiitv/algos#694]
#### This issue is about [Double Ended Queue](https://www.includehelp.com/data-structure-tutorial/dequeue-queue-in-data-structure-using-c-and-cpp.aspx)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by Monik09** [comment]
i want to work on this issue. @yashshah2820

**Comment by yashshah2820** [comment]
@Monik09 in the link add the path in the repo you will want the algorithm to be added instead of an external link that is in the issuing body.

**Comment by Monik09** [comment]
@yashshah2820 There is no folder for double ended queue in iiitv/algos repo...

**Comment by yashshah2820** [comment]
@Monik09 GFI 👍

**Comment by Monik09** [comment]
@yashshah2820 can you please reassign this issue, it was unassigned by mistake. sorry for the inconvenience.
