### ISSUE TITLE
The Longest Common Subsequence [C]

### ISSUE THREAD

**Issue by RajuKoushik** [iiitv/algos#7]
LCS Problem Statement: Given two sequences, find the length of longest subsequence present in both of them. A subsequence is a sequence that appears in the same relative order, but not necessarily contiguous. For example, “abc”, “abg”, “bdf”, “aeg”, ‘”acefg”, .. etc are subsequences of “abcdefg”. So a string of length n has 2^n different possible subsequences.

Examples:
LCS for input Sequences “ABCDGH” and “AEDFHR” is “ADH” of length 3.
LCS for input Sequences “AGGTAB” and “GXTXAYB” is “GTAB” of length 4.

**Comment by aviaryan** [comment]
Do you want to do this @RajuKoushik ?

**Comment by yashLadha** [comment]
I can work upon this.

**Comment by singhpratyush** [comment]
Removing all other languages than C. Please open issues if you wish to implement in other language.
