### ISSUE TITLE
Define a merge policy

### ISSUE THREAD

**Issue by aviaryan** [iiitv/algos#70]
We need a merge policy to fix how we are going to merge PRs. Here's my proposal - 

1. One squashed commit merge with PR. 
2. Even if PR contains multiple type of changes, it should reflect only a single topic and Rule 1 shall still withhold on it.

##### Why squashed merge ?

It preserves both the author as well as the committer, something that can be very useful. 
Also one commit per PR provides the cleanest commit history possible.

-----

@singhpratyush views?

**Comment by yashLadha** [comment]
I told you before also. @aviaryan

**Comment by singhpratyush** [comment]
One commit policy seems promising. But I think that we may also go with rebase if PR contains only one commit with relevant commit message.

Also, shall we set the commit message format for various types of commits (doc update, new algorithm, improved algorithm, etc.)?

**Comment by yashLadha** [comment]
One commit should have all the necessary changes that need for inclusion of that algo. Commits like added spacing, minor changes gives bad impression. As every commit should add some new thing to the repo, not some reformatting. what do u think @singhpratyush

**Comment by singhpratyush** [comment]
@yashLadha : That is exactly why we are planning to squash things in the first place.

**Comment by yashLadha** [comment]
It would be great @singhpratyush

**Comment by aviaryan** [comment]
> One commit policy seems promising. But I think that we may also go with rebase if PR contains only one commit with relevant commit message.

:+1:

> Also, shall we set the commit message format for various types of commits (doc update, new algorithm, improved algorithm, etc.)?

That discussion would go in a separate thread.

**Comment by singhpratyush** [comment]
@aviaryan : Do we need a document for the policy?

**Comment by yashLadha** [comment]
Sir , what we can do is that we can tell the user to rebase at the end . When merging will be done.

**Comment by aviaryan** [comment]
@yashLadha I am not sure if everyone will be able to do that. We don't want our contributors to be scared away by the complicities of git. 

@singhpratyush We can create a MAINTAINER.md and include this info here. This will be helpful for future maintainers.

**Comment by yashLadha** [comment]
Sir, but there is a need to do. Because when i contributed to some other organisation, i have to learn to rebase the commits, as it is a standard practice to know. It would be better if contributors know about it. And it is just 2 more commands to use. @aviaryan

**Comment by singhpratyush** [comment]
Let me sum this up - 
  
**Squash when**
* Many commits.
* Single commit with some improper commit message.

**Rebase when**
* Single commit with a good commit message.
