### ISSUE TITLE
Searching / Binary Search[C++]

### ISSUE THREAD

**Issue by himanshusanecha** [iiitv/algos#703]
#### This issue is about [Searching / Binary Search[C++]](https://www.geeksforgeeks.org/binary-search/).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by jatin0814** [comment]
@himanshusanecha this issue already exists. #643

**Comment by yashshah2820** [comment]
@himanshusanecha please don't make a duplicate issue first, look if a similar issue already exists or not.

**Comment by himanshusanecha** [comment]
Sorry @yashshah2820
