### ISSUE TITLE
Coin Change [C++]

### ISSUE THREAD

**Issue by darshanhande11** [iiitv/algos#709]
#### This issue is about Coin Change [C++] (https://github.com/iiitv/algos/tree/master/counting_sort).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by darshanhande11** [comment]
@iiitv/project-maintainers I want to work on this issue

**Comment by yashshah2820** [comment]
@darshanhande11 don't add geeks-for-geeks or any other links instead add the link where the algorithm will be updated or added in the algos repository

**Comment by darshanhande11** [comment]
@yashshah2820 Sir, I have updated the link. Is the link correct now?

**Comment by yashshah2820** [comment]
we already have a code implemented in C, having a CPP code will not make much difference, you work on other issues 😄

**Comment by darshanhande11** [comment]
okay sir.
