### ISSUE TITLE
Disjoint_union_set[C]

### ISSUE THREAD

**Issue by vidit2512** [iiitv/algos#716]
#### This issue is about [Disjoint_union_set](https://github.com/iiitv/algos).

- [x] Issue Title is in form `Disjoint_union_set [C]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by vidit2512** [comment]
@iiitv/project-maintainers  I want to work on this issue.

**Comment by anujpuri72** [comment]
@vidit2512 GFI 👍
