### ISSUE TITLE
Breadth First Search in a Graph [Java]

### ISSUE THREAD

**Issue by sandeep201451066** [iiitv/algos#73]
https://en.wikipedia.org/wiki/Breadth-first_search

**Comment by jsroyal** [comment]
@sandeep 201451066
Do you want to implement?
If yes then assign your self here.

**Comment by jsroyal** [comment]
@sandeep201451066
Do you want to implement?
If yes then assign your self here.

**Comment by singhpratyush** [comment]
> If yes then assign your self here.

He has already done that.

**Comment by jsroyal** [comment]
Oh' sorry I was seeing in mobile and I just skipped that line and also did not visible in mobile assigne lebel.

**Comment by singhpratyush** [comment]
@sandeep201451066 : Please work on one issue at a time.

**Comment by sandeep201451066** [comment]
I am working on BFS.

**Comment by singhpratyush** [comment]
But you haven't closed #72 yet (on which you are currently working). So kindly unassign yourself.

**Comment by jsroyal** [comment]
@singhpratyush it has been such long time, I implemented and can send PR? 
also, I'm not able to assign to me.
