### ISSUE TITLE
Readme edit : Two rows for queue in readme table instead of one. 

### ISSUE THREAD

**Issue by nlok5923** [iiitv/algos#737]
#### This issue is about same rows for queue in readme file,

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by nlok5923** [comment]
@iiitv/project-maintainers  i would like to work on this issue.

**Comment by ishanksoni** [comment]
@nlok5923 You have already assigned for issue #687 , that is quit similar to this issue. I don't think this issue is needed.

**Comment by yashshah2820** [comment]
I agree this issue is redundant.
