### ISSUE TITLE
Sorting/Heapsort[c#]

### ISSUE THREAD

**Issue by nlok5923** [iiitv/algos#748]
#### This issue is about[Sorting/heapsort](https://www.tutorialspoint.com/heap-sort-in-chash)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by nlok5923** [comment]
@iiitv/project-maintainers please do let me know about the validity of this issue.

**Comment by yashshah2820** [comment]
@nlok5923 we already have heapsort algo written in four languages, I don't think we need more 😅
