### ISSUE TITLE
Sorting/Heapsort[Golang]

### ISSUE THREAD

**Issue by nlok5923** [iiitv/algos#749]
#### This issue is about [sorting/Heapsort](https://golangbyexample.com/heapsort-in-golang/)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] i searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by nlok5923** [comment]
@iiitv/project-maintainers please do let me know about the validity of this issue.

**Comment by yashshah2820** [comment]
@nlok check my comment on the #748
