### ISSUE TITLE
Breadth First Search in a Graph [C#]

### ISSUE THREAD

**Issue by The-Keshav-Agarwal** [iiitv/algos#756]
#### This issue is about [Breadth First Search](https://www.dotnetforall.com/breadth-first-searchbfs-in-c/).

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by anujpuri72** [comment]
GFI @The-Keshav-Agarwal

**Comment by The-Keshav-Agarwal** [comment]
sorry @anujpuri72 sir, but actually i don't want to work on this issue. I saw that there is no code in C# for BFS, so i created this issue for others😂😂
