### ISSUE TITLE
breadth_first_search/Shortest Distance between two nodes (Java)

### ISSUE THREAD

**Issue by marizvi** [iiitv/algos#774]
#### This issue is about [Algo/Graph Data Structure/BFS].

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This breadth_first_search/Shortest Distance is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by marizvi** [comment]
Hello,
I would like to work on this issue, kindly assign me this issue under contribute-a-thon'21.

**Comment by vidit2512** [comment]
@marizvi This algorithm is already [here]( I guess https://github.com/iiitv/algos/blob/master/breadth_first_search/BreadthFirstSearch.cpp )
