### ISSUE TITLE
Binary Tree/Mirror of a Binary Tree (JAVA)

### ISSUE THREAD

**Issue by marizvi** [iiitv/algos#777]
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

Kindly assign me this issue under Contribute-a-thon'21

**Comment by vidit2512** [comment]
@marizvi GFI 👍

**Comment by vidit2512** [comment]
Kindly attach the input/output screenshots of the algorithm here.

**Comment by marizvi** [comment]
yeah sure.

**Comment by marizvi** [comment]
![Screenshot 2021-10-05 011737](https://user-images.githubusercontent.com/76868116/135914834-96e5e076-affe-4e40-b2f1-6397bcd2cf81.png)

This input is already a part of code.
The output is below..

**Comment by marizvi** [comment]
![Screenshot 2021-10-05 011703](https://user-images.githubusercontent.com/76868116/135914977-d7c44320-b5b4-4faf-9f70-d33eff986047.png)

**Comment by marizvi** [comment]
![Screenshot 2021-10-05 011945](https://user-images.githubusercontent.com/76868116/135915116-73e2789c-8aba-4a2f-8609-ee40e5a74bbc.png)

**Comment by marizvi** [comment]
is this much fine sir?

**Comment by vidit2512** [comment]
LGTM
