### ISSUE TITLE
Sort/Counting Sort [CPP]

### ISSUE THREAD

**Issue by marizvi** [iiitv/algos#778]
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Sort/Counting Sort [CPP]  is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

Kindly assign me this issue under contribute-a-thon'21.

**Comment by vidit2512** [comment]
The algorithm is already present [here](https://github.com/iiitv/algos/blob/master/counting_sort/counting_sort.c).
