### ISSUE TITLE
Modular Exponentiation [C++]

### ISSUE THREAD

**Issue by roeticvampire** [iiitv/algos#784]
#### This issue is about Modular Exponentiation ( [here](http://www.geeksforgeeks.org/modular-exponentiation-power-in-modular-arithmetic/) ).

- [x] Issue Title is in form `Algo/DS Name [ C++ ]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by vidit2512** [comment]
The same algorithm is present [here](https://github.com/iiitv/algos/blob/master/modular_exponential/modular_exponential.c)
