### ISSUE TITLE
Backtracking algorithm (N-Queen Problem) [CPP]

### ISSUE THREAD

**Issue by mohitkyadav** [iiitv/algos#81]
A general solution of the N-Queen problem (any board of n X n) in C++ with backtracking.

https://en.wikipedia.org/wiki/Eight_queens_puzzle

**Comment by singhpratyush** [comment]
@mohitkyadav : What `n` will you be working with?

**Comment by mohitkyadav** [comment]
@singhpratyush  n is the side of the square chess board,

**Comment by mohitkyadav** [comment]
@singhpratyush   Can I use global variables?

**Comment by singhpratyush** [comment]
No. But you may use global constants if you need.

**Comment by aviaryan** [comment]
Fixed by #87
