### ISSUE TITLE
Updated Queue(Format) and Breadth First Traversal[JAVA] in README

### ISSUE THREAD

**Issue by aryanargupta** [iiitv/algos#816]
#### This issue is about README of [Queue] and Breadth First Traversal[JAVA]. There were multiple instances of Queue in the table which I have merged, as well as updated the check mark for the Breadth First traversal in JAVA recently added by satyacasm. Hence, I request to assign this issue to me so that I can send the PR and resolve the issues ASAP.

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by aryanargupta** [comment]
Also, added a correct link for Breadth First Traversal as the old link is probably not existing now.

**Comment by AkhileshManda** [comment]
@kalashshah

**Comment by kalashshah** [comment]
GFI 👍
