### ISSUE TITLE
Further Updation in README for BFS, BFT, Dijkstra, Heap Sort, Insertion Sort, Fibonacci Number, Queue

### ISSUE THREAD

**Issue by aryanargupta** [iiitv/algos#819]
#### This issue is about updation in README for [BFS] (Cpp), [BFT] (Cpp), [Dijkstra] (JS), [Heap Sort] (Cpp), [Insertion Sort] (Cpp), [Fibonacci Number] (C and JS), [Queue] (Cpp)

- [x] Issue Title is in form `Algo/DS Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by AkhileshManda** [comment]
GFI @aryanargupta
