### ISSUE TITLE
Stack [JAVA]

### ISSUE THREAD

**Issue by Monal5031** [iiitv/algos#93]
https://en.wikipedia.org/wiki/Stack_(abstract_data_type)

Following Functionalities I will add:
* Display stack elements
* Push (Adding element to top of stack)
* Pop (Removing element from top of stack)
* Peek
* Get size

Will create a separate class for it and test in Main class.
Any suggestions over any particular thing I should use?

**Comment by Monal5031** [comment]
@singhpratyush @aviaryan @jsroyal @aashutoshrathi 
Shall I use array or linked list for its implementation?

**Comment by jsroyal** [comment]
The Linked list would be good if you can implement.

**Comment by Monal5031** [comment]
@aashutoshrathi I will assign it myself when I am done with my current assignments, until then if anyone else is interested they might take the issue. 😄
