### ISSUE TITLE
Kadane's Algorithm (Largest Sum Contiguous Subarray problem) [CPP]

### ISSUE THREAD

**Issue by mohitkyadav** [iiitv/algos#98]
A popular Dynamic programming algorithm to find a largest sum contiguous subarray.

https://kartikkukreja.wordpress.com/2013/06/17/kadanes-algorithm/

**Comment by Monal5031** [comment]
@mohitkyadav this algorithm is already implemented in java.
Don't create a separate folder with this name add it in the same folder

**Comment by mohitkyadav** [comment]
Well I didn't notice that. Thanks @Monal5031

**Comment by Monal5031** [comment]
@mohitkyadav This algorithm is implemented in JAVA you can still implement it in c++.
I was just saying to be sure that you add it in that folder only
